// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV42IJ8bGd74h10M2tzh0L-mgMjVSwfXY',
    appId: '1:549261373635:web:4d89ba9fd992f8280f7276',
    messagingSenderId: '549261373635',
    projectId: 'flutter-proj-amal',
    authDomain: 'flutter-proj-amal.firebaseapp.com',
    storageBucket: 'flutter-proj-amal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3kSJtvNUTnSsY53HsqC-s4kw77GA_3k',
    appId: '1:549261373635:android:349d2b08fb4605c20f7276',
    messagingSenderId: '549261373635',
    projectId: 'flutter-proj-amal',
    storageBucket: 'flutter-proj-amal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGsiTIR--kJtrAmGcAnuf-eqLQFWciOQ',
    appId: '1:549261373635:ios:c24dce259b5db8cd0f7276',
    messagingSenderId: '549261373635',
    projectId: 'flutter-proj-amal',
    storageBucket: 'flutter-proj-amal.appspot.com',
    iosClientId:
        '549261373635-ipp4l0dig30o1kv1ot9joieequkktrbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGsiTIR--kJtrAmGcAnuf-eqLQFWciOQ',
    appId: '1:549261373635:ios:c24dce259b5db8cd0f7276',
    messagingSenderId: '549261373635',
    projectId: 'flutter-proj-amal',
    storageBucket: 'flutter-proj-amal.appspot.com',
    iosClientId:
        '549261373635-ipp4l0dig30o1kv1ot9joieequkktrbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
